/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author brikz
 */
public class CreditosTela extends javax.swing.JFrame {

    /**
     * Creates new form CreditosTela
     */
    public CreditosTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        selecaoUnidadeBotao = new javax.swing.JLabel();
        selecaoUnidadeBotao1 = new javax.swing.JLabel();
        selecaoUnidadeBotao2 = new javax.swing.JLabel();
        selecaoUnidadeBotao3 = new javax.swing.JLabel();
        selecaoUnidadeBotao4 = new javax.swing.JLabel();
        selecaoUnidadeBotao5 = new javax.swing.JLabel();
        selecaoUnidadeBotao6 = new javax.swing.JLabel();
        selecaoUnidadeBotao7 = new javax.swing.JLabel();
        selecaoUnidadeBotao9 = new javax.swing.JLabel();
        selecaoUnidadeBotao8 = new javax.swing.JLabel();
        selecaoUnidadeBotao10 = new javax.swing.JLabel();
        selecaoUnidadeBotao11 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon("/home/brikz/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/Imagens/MenuIcon.png")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(180, 90, 50, 50);

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setFont(new java.awt.Font("Montserrat SemiBold", 1, 40)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("CRÉDITOS");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(146, 63, 879, 107);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(968, 705));

        selecaoUnidadeBotao.setFont(new java.awt.Font("Montserrat Thin", 1, 18)); // NOI18N
        selecaoUnidadeBotao.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao.setText("Daniel Briquez e Diogo Carvalho");
        selecaoUnidadeBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotaoMouseClicked(evt);
            }
        });

        selecaoUnidadeBotao1.setFont(new java.awt.Font("Montserrat SemiBold", 2, 18)); // NOI18N
        selecaoUnidadeBotao1.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao1.setText("Modelagem Orientada a Objetos");
        selecaoUnidadeBotao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao1MouseClicked(evt);
            }
        });

        selecaoUnidadeBotao2.setFont(new java.awt.Font("Montserrat Thin", 1, 18)); // NOI18N
        selecaoUnidadeBotao2.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao2.setText("Fernando Freitas, Bruno Teruya");
        selecaoUnidadeBotao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao2MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao2MouseExited(evt);
            }
        });

        selecaoUnidadeBotao3.setFont(new java.awt.Font("Montserrat SemiBold", 2, 18)); // NOI18N
        selecaoUnidadeBotao3.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao3.setText("Banco de Dados");
        selecaoUnidadeBotao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao3MouseExited(evt);
            }
        });

        selecaoUnidadeBotao4.setFont(new java.awt.Font("Montserrat Thin", 1, 18)); // NOI18N
        selecaoUnidadeBotao4.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao4.setText("Daniel Briquez");
        selecaoUnidadeBotao4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao4MouseExited(evt);
            }
        });

        selecaoUnidadeBotao5.setFont(new java.awt.Font("Montserrat SemiBold", 2, 18)); // NOI18N
        selecaoUnidadeBotao5.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao5.setText("Front End");
        selecaoUnidadeBotao5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao5MouseExited(evt);
            }
        });

        selecaoUnidadeBotao6.setFont(new java.awt.Font("Montserrat Thin", 1, 18)); // NOI18N
        selecaoUnidadeBotao6.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao6.setText("Gustavo Yudji e Bruno Teruya");
        selecaoUnidadeBotao6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao6MouseExited(evt);
            }
        });

        selecaoUnidadeBotao7.setFont(new java.awt.Font("Montserrat SemiBold", 2, 18)); // NOI18N
        selecaoUnidadeBotao7.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao7.setText("Back End");
        selecaoUnidadeBotao7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao7MouseExited(evt);
            }
        });

        selecaoUnidadeBotao9.setFont(new java.awt.Font("Montserrat SemiBold", 2, 18)); // NOI18N
        selecaoUnidadeBotao9.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao9.setText("Design e Artes");
        selecaoUnidadeBotao9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao9MouseExited(evt);
            }
        });

        selecaoUnidadeBotao8.setFont(new java.awt.Font("Montserrat Thin", 1, 18)); // NOI18N
        selecaoUnidadeBotao8.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao8.setText("Diogo Carvalho");
        selecaoUnidadeBotao8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao8MouseExited(evt);
            }
        });

        selecaoUnidadeBotao10.setFont(new java.awt.Font("Montserrat Thin", 1, 18)); // NOI18N
        selecaoUnidadeBotao10.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao10.setText("Fernando Freitas");
        selecaoUnidadeBotao10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao10MouseExited(evt);
            }
        });

        selecaoUnidadeBotao11.setFont(new java.awt.Font("Montserrat SemiBold", 2, 18)); // NOI18N
        selecaoUnidadeBotao11.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao11.setText("Documentação");
        selecaoUnidadeBotao11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotao11MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecaoUnidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao5, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao3, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao7, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao6, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao9, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecaoUnidadeBotao4, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecaoUnidadeBotao8, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoUnidadeBotao10, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecaoUnidadeBotao11, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(selecaoUnidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(selecaoUnidadeBotao2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(selecaoUnidadeBotao5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selecaoUnidadeBotao1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(selecaoUnidadeBotao3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(selecaoUnidadeBotao8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(selecaoUnidadeBotao7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(selecaoUnidadeBotao6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(selecaoUnidadeBotao9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(selecaoUnidadeBotao10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(selecaoUnidadeBotao11, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(selecaoUnidadeBotao4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(150, 190, 880, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1240, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void selecaoUnidadeBotao11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao11MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao11MouseExited

    private void selecaoUnidadeBotao11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao11MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao11MouseEntered

    private void selecaoUnidadeBotao11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao11MouseClicked

    private void selecaoUnidadeBotao10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao10MouseExited

    private void selecaoUnidadeBotao10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao10MouseEntered

    private void selecaoUnidadeBotao10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao10MouseClicked

    private void selecaoUnidadeBotao8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao8MouseExited

    private void selecaoUnidadeBotao8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao8MouseEntered

    private void selecaoUnidadeBotao8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao8MouseClicked

    private void selecaoUnidadeBotao9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao9MouseExited

    private void selecaoUnidadeBotao9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao9MouseEntered

    private void selecaoUnidadeBotao9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao9MouseClicked

    private void selecaoUnidadeBotao7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao7MouseExited

    private void selecaoUnidadeBotao7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao7MouseEntered

    private void selecaoUnidadeBotao7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao7MouseClicked

    private void selecaoUnidadeBotao6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao6MouseExited

    private void selecaoUnidadeBotao6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao6MouseEntered

    private void selecaoUnidadeBotao6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao6MouseClicked

    private void selecaoUnidadeBotao5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao5MouseExited

    private void selecaoUnidadeBotao5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao5MouseEntered

    private void selecaoUnidadeBotao5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao5MouseClicked

    private void selecaoUnidadeBotao4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao4MouseExited

    private void selecaoUnidadeBotao4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao4MouseEntered

    private void selecaoUnidadeBotao4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao4MouseClicked

    private void selecaoUnidadeBotao3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao3MouseExited

    private void selecaoUnidadeBotao3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao3MouseEntered

    private void selecaoUnidadeBotao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao3MouseClicked

    private void selecaoUnidadeBotao2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao2MouseExited

    private void selecaoUnidadeBotao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao2MouseClicked

    private void selecaoUnidadeBotao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotao1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_selecaoUnidadeBotao1MouseClicked

    private void selecaoUnidadeBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotaoMouseClicked
        setVisible(false);
        new EscolhaUnidadesTela().setVisible(true);
    }//GEN-LAST:event_selecaoUnidadeBotaoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        new MenuPrincipalTela().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditosTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel selecaoUnidadeBotao;
    private javax.swing.JLabel selecaoUnidadeBotao1;
    private javax.swing.JLabel selecaoUnidadeBotao10;
    private javax.swing.JLabel selecaoUnidadeBotao11;
    private javax.swing.JLabel selecaoUnidadeBotao2;
    private javax.swing.JLabel selecaoUnidadeBotao3;
    private javax.swing.JLabel selecaoUnidadeBotao4;
    private javax.swing.JLabel selecaoUnidadeBotao5;
    private javax.swing.JLabel selecaoUnidadeBotao6;
    private javax.swing.JLabel selecaoUnidadeBotao7;
    private javax.swing.JLabel selecaoUnidadeBotao8;
    private javax.swing.JLabel selecaoUnidadeBotao9;
    // End of variables declaration//GEN-END:variables
}
