/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import java.awt.Color;

/**
 *
 * @author brikz
 */
public class EscolhaUnidadesTela extends javax.swing.JFrame {

    /**
     * Creates new form EscolhaUnidadesTela
     */
    public EscolhaUnidadesTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jogarU2Botao1 = new javax.swing.JButton();
        jTextField8 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        unidade1EnterBotao = new javax.swing.JLabel();
        SubtituloU2a = new javax.swing.JLabel();
        unidade4EnterBotao = new javax.swing.JLabel();
        unidade2EnterBotao = new javax.swing.JLabel();
        SubtituloU1 = new javax.swing.JLabel();
        SubtituloU3 = new javax.swing.JLabel();
        unidade3EnterBotao = new javax.swing.JLabel();
        SubtituloU4 = new javax.swing.JLabel();
        SubtituloU2b = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        unidade5EnterBotao = new javax.swing.JLabel();
        SubtituloU8 = new javax.swing.JLabel();
        unidade8EnterBotao = new javax.swing.JLabel();
        SubtituloU7 = new javax.swing.JLabel();
        unidade7EnterBotao = new javax.swing.JLabel();
        SubtituloU6 = new javax.swing.JLabel();
        unidade6EnterBotao = new javax.swing.JLabel();
        SubtituloU5 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        sairSelecaoUnidadeBotao = new javax.swing.JButton();

        jogarU2Botao1.setText("Jogar");
        jogarU2Botao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jogarU2Botao1ActionPerformed(evt);
            }
        });

        jTextField8.setBackground(new java.awt.Color(0, 0, 0));
        jTextField8.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(148, 87, 242));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField8.setText("0%");
        jTextField8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextField1.setBackground(new java.awt.Color(85, 51, 141));
        jTextField1.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("SELEÇÃO DE UNIDADE");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        unidade1EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade1EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade1EnterBotao.setText("Unidade 1");
        unidade1EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade1EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade1EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade1EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU2a.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU2a.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU2a.setText("Arquitetura de SGBD e ");

        unidade4EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade4EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade4EnterBotao.setText("Unidade 4");
        unidade4EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade4EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade4EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade4EnterBotaoMouseExited(evt);
            }
        });

        unidade2EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade2EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade2EnterBotao.setText("Unidade 2");
        unidade2EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade2EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade2EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade2EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU1.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU1.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU1.setText("Introdução aos DBMS's");

        SubtituloU3.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU3.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU3.setText("Introdução aos DBMS's");

        unidade3EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade3EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade3EnterBotao.setText("Unidade 3");
        unidade3EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade3EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade3EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade3EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU4.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU4.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU4.setText("Introdução aos DBMS's");

        SubtituloU2b.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU2b.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU2b.setText("Modelo Relacional");

        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(148, 87, 242));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setText("0%");
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(148, 87, 242));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setText("0%");
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField6.setBackground(new java.awt.Color(0, 0, 0));
        jTextField6.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(148, 87, 242));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField6.setText("0%");
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField7.setBackground(new java.awt.Color(0, 0, 0));
        jTextField7.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(148, 87, 242));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField7.setText("0%");
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubtituloU1)
                            .addComponent(SubtituloU4)
                            .addComponent(SubtituloU3)
                            .addComponent(SubtituloU2a))
                        .addGap(159, 159, 159))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(unidade1EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(unidade2EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(SubtituloU2b)
                                    .addComponent(unidade3EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(unidade4EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidade1EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloU1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidade2EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloU2a)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(SubtituloU2b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unidade3EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addComponent(SubtituloU3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(unidade4EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloU4)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel3.setPreferredSize(new java.awt.Dimension(474, 532));

        unidade5EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade5EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade5EnterBotao.setText("Unidade 5");
        unidade5EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade5EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade5EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade5EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU8.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU8.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU8.setText("Boas Práticas e Normalização");

        unidade8EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade8EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade8EnterBotao.setText("Unidade 8");
        unidade8EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade8EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade8EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade8EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU7.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU7.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU7.setText("Queries Multi-Tabelas");

        unidade7EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade7EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade7EnterBotao.setText("Unidade 7");
        unidade7EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade7EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade7EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade7EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU6.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU6.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU6.setText("SQL - DML");

        unidade6EnterBotao.setFont(new java.awt.Font("Ramabhadra", 1, 36)); // NOI18N
        unidade6EnterBotao.setForeground(new java.awt.Color(255, 255, 255));
        unidade6EnterBotao.setText("Unidade 6");
        unidade6EnterBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unidade6EnterBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unidade6EnterBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                unidade6EnterBotaoMouseExited(evt);
            }
        });

        SubtituloU5.setFont(new java.awt.Font("SansSerif", 2, 18)); // NOI18N
        SubtituloU5.setForeground(new java.awt.Color(255, 255, 255));
        SubtituloU5.setText("Álgebra Relacional");

        jTextField9.setBackground(new java.awt.Color(0, 0, 0));
        jTextField9.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField9.setForeground(new java.awt.Color(148, 87, 242));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField9.setText("0%");
        jTextField9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField10.setBackground(new java.awt.Color(0, 0, 0));
        jTextField10.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(148, 87, 242));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField10.setText("0%");
        jTextField10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField11.setBackground(new java.awt.Color(0, 0, 0));
        jTextField11.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(148, 87, 242));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField11.setText("0%");
        jTextField11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTextField12.setBackground(new java.awt.Color(0, 0, 0));
        jTextField12.setFont(new java.awt.Font("Montserrat SemiBold", 1, 36)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(148, 87, 242));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField12.setText("0%");
        jTextField12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidade6EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubtituloU5)
                    .addComponent(SubtituloU8)
                    .addComponent(SubtituloU7)
                    .addComponent(SubtituloU6)
                    .addComponent(unidade5EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidade7EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidade8EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidade5EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloU5)
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidade6EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloU6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unidade7EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloU7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(unidade8EnterBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubtituloU8)
                .addGap(63, 63, 63))
        );

        sairSelecaoUnidadeBotao.setIcon(new javax.swing.ImageIcon("/home/brikz/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/Imagens/closeIcon.png")); // NOI18N
        sairSelecaoUnidadeBotao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sairSelecaoUnidadeBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairSelecaoUnidadeBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(sairSelecaoUnidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(124, 124, 124))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(sairSelecaoUnidadeBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jogarU2Botao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jogarU2Botao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jogarU2Botao1ActionPerformed

    private void unidade1EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade1EnterBotaoMouseEntered
        unidade1EnterBotao.setForeground(new Color(147,87,242));    // TODO add your handling code here:
    }//GEN-LAST:event_unidade1EnterBotaoMouseEntered

    private void unidade1EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade1EnterBotaoMouseExited
        unidade1EnterBotao.setForeground(Color.white);     // TODO add your handling code here:
    }//GEN-LAST:event_unidade1EnterBotaoMouseExited

    private void unidade4EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade4EnterBotaoMouseEntered
        unidade4EnterBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade4EnterBotaoMouseEntered

    private void unidade4EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade4EnterBotaoMouseExited
        unidade4EnterBotao.setForeground(Color.white); 
    }//GEN-LAST:event_unidade4EnterBotaoMouseExited

    private void unidade2EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade2EnterBotaoMouseEntered
        unidade2EnterBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade2EnterBotaoMouseEntered

    private void unidade2EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade2EnterBotaoMouseExited
        unidade2EnterBotao.setForeground(Color.white); 
    }//GEN-LAST:event_unidade2EnterBotaoMouseExited

    private void unidade3EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade3EnterBotaoMouseEntered
        unidade3EnterBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade3EnterBotaoMouseEntered

    private void unidade3EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade3EnterBotaoMouseExited
        unidade3EnterBotao.setForeground(Color.white); 
    }//GEN-LAST:event_unidade3EnterBotaoMouseExited

    private void unidade8EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade8EnterBotaoMouseEntered
        unidade8EnterBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade8EnterBotaoMouseEntered

    private void unidade8EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade8EnterBotaoMouseExited
        unidade8EnterBotao.setForeground(Color.white); 
    }//GEN-LAST:event_unidade8EnterBotaoMouseExited

    private void unidade6EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade6EnterBotaoMouseEntered
        unidade6EnterBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade6EnterBotaoMouseEntered

    private void unidade6EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade6EnterBotaoMouseExited
        unidade6EnterBotao.setForeground(Color.white); 
    }//GEN-LAST:event_unidade6EnterBotaoMouseExited

    private void unidade5EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade5EnterBotaoMouseEntered
        unidade5EnterBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade5EnterBotaoMouseEntered

    private void unidade5EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade5EnterBotaoMouseExited
        unidade5EnterBotao.setForeground(Color.white); 
    }//GEN-LAST:event_unidade5EnterBotaoMouseExited

    private void unidade7EnterBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade7EnterBotaoMouseEntered
        unidade7EnterBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_unidade7EnterBotaoMouseEntered

    private void unidade7EnterBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade7EnterBotaoMouseExited
        unidade7EnterBotao.setForeground(Color.white); 
    }//GEN-LAST:event_unidade7EnterBotaoMouseExited

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void sairSelecaoUnidadeBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairSelecaoUnidadeBotaoActionPerformed
        setVisible(false);
        new MenuPrincipalTela().setVisible(true);
    }//GEN-LAST:event_sairSelecaoUnidadeBotaoActionPerformed

    private void unidade1EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade1EnterBotaoMouseClicked
        setVisible(false);
       new U1EnterTela().setVisible(true);      
    }//GEN-LAST:event_unidade1EnterBotaoMouseClicked

    private void unidade2EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade2EnterBotaoMouseClicked
        setVisible(false);
       new U2EnterTela().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_unidade2EnterBotaoMouseClicked

    private void unidade3EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade3EnterBotaoMouseClicked
        setVisible(false);
       new U3EnterTela().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_unidade3EnterBotaoMouseClicked

    private void unidade4EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade4EnterBotaoMouseClicked
        setVisible(false);
       new U4EnterTela().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_unidade4EnterBotaoMouseClicked

    private void unidade5EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade5EnterBotaoMouseClicked
        setVisible(false);
       new U5EnterTela().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_unidade5EnterBotaoMouseClicked

    private void unidade6EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade6EnterBotaoMouseClicked
        setVisible(false);
       new U6EnterTela().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_unidade6EnterBotaoMouseClicked

    private void unidade7EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade7EnterBotaoMouseClicked
        setVisible(false);
       new U7EnterTela().setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_unidade7EnterBotaoMouseClicked

    private void unidade8EnterBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unidade8EnterBotaoMouseClicked
         setVisible(false);
       new U8EnterTela().setVisible(true);      
    }//GEN-LAST:event_unidade8EnterBotaoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolhaUnidadesTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolhaUnidadesTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SubtituloU1;
    private javax.swing.JLabel SubtituloU2a;
    private javax.swing.JLabel SubtituloU2b;
    private javax.swing.JLabel SubtituloU3;
    private javax.swing.JLabel SubtituloU4;
    private javax.swing.JLabel SubtituloU5;
    private javax.swing.JLabel SubtituloU6;
    private javax.swing.JLabel SubtituloU7;
    private javax.swing.JLabel SubtituloU8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jogarU2Botao1;
    private javax.swing.JButton sairSelecaoUnidadeBotao;
    private javax.swing.JLabel unidade1EnterBotao;
    private javax.swing.JLabel unidade2EnterBotao;
    private javax.swing.JLabel unidade3EnterBotao;
    private javax.swing.JLabel unidade4EnterBotao;
    private javax.swing.JLabel unidade5EnterBotao;
    private javax.swing.JLabel unidade6EnterBotao;
    private javax.swing.JLabel unidade7EnterBotao;
    private javax.swing.JLabel unidade8EnterBotao;
    // End of variables declaration//GEN-END:variables
}
