/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;
import java.awt.Color;


public class MenuPrincipalTela extends javax.swing.JFrame {
    

    /**
     * Creates new form MenuPrincipalTela
     */
    public MenuPrincipalTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        documentacaoBotao = new javax.swing.JLabel();
        selecaoJogadorBotao = new javax.swing.JLabel();
        creditosBotao = new javax.swing.JLabel();
        selecaoUnidadeBotao = new javax.swing.JLabel();
        sairBotao = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tutorialBotao = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jPanel1.setPreferredSize(new java.awt.Dimension(948, 697));
        jPanel1.setLayout(null);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));
        jSeparator1.setMinimumSize(new java.awt.Dimension(944, 10));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(5, 105, 940, 10);

        jButton1.setIcon(new javax.swing.ImageIcon("/home/brikz/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/Imagens/closeIcon.png")); // NOI18N
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setMaximumSize(new java.awt.Dimension(54, 54));
        jButton1.setMinimumSize(new java.awt.Dimension(54, 54));
        jButton1.setPreferredSize(new java.awt.Dimension(54, 54));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 30, 54, 54);

        documentacaoBotao.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        documentacaoBotao.setForeground(new java.awt.Color(255, 255, 255));
        documentacaoBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        documentacaoBotao.setText("Documentação");
        documentacaoBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                documentacaoBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                documentacaoBotaoMouseExited(evt);
            }
        });
        jPanel1.add(documentacaoBotao);
        documentacaoBotao.setBounds(49, 332, 840, 70);

        selecaoJogadorBotao.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        selecaoJogadorBotao.setForeground(new java.awt.Color(255, 255, 255));
        selecaoJogadorBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoJogadorBotao.setText("Seleção de Jogador");
        selecaoJogadorBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoJogadorBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoJogadorBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoJogadorBotaoMouseExited(evt);
            }
        });
        jPanel1.add(selecaoJogadorBotao);
        selecaoJogadorBotao.setBounds(49, 262, 840, 70);

        creditosBotao.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        creditosBotao.setForeground(new java.awt.Color(255, 255, 255));
        creditosBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditosBotao.setText("Créditos");
        creditosBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                creditosBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                creditosBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                creditosBotaoMouseExited(evt);
            }
        });
        jPanel1.add(creditosBotao);
        creditosBotao.setBounds(49, 472, 840, 70);

        selecaoUnidadeBotao.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        selecaoUnidadeBotao.setForeground(new java.awt.Color(255, 255, 255));
        selecaoUnidadeBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selecaoUnidadeBotao.setText("Seleção de Unidades");
        selecaoUnidadeBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                selecaoUnidadeBotaoMouseExited(evt);
            }
        });
        jPanel1.add(selecaoUnidadeBotao);
        selecaoUnidadeBotao.setBounds(49, 192, 840, 70);

        sairBotao.setBackground(new java.awt.Color(0, 0, 0));
        sairBotao.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        sairBotao.setForeground(new java.awt.Color(255, 255, 255));
        sairBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sairBotao.setText("Sair do Jogo");
        sairBotao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        sairBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sairBotaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                sairBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sairBotaoMouseExited(evt);
            }
        });
        jPanel1.add(sairBotao);
        sairBotao.setBounds(49, 542, 840, 70);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/brikz/NetBeansProjects/mavenproject1/src/main/java/com/mycompany/mavenproject1/Imagens/TopoMenu.png")); // NOI18N
        jLabel2.setAlignmentY(0.0F);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(4, 5, 950, 100);

        tutorialBotao.setFont(new java.awt.Font("Montserrat Thin", 1, 36)); // NOI18N
        tutorialBotao.setForeground(new java.awt.Color(255, 255, 255));
        tutorialBotao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tutorialBotao.setText("Tutorial");
        tutorialBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tutorialBotaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tutorialBotaoMouseExited(evt);
            }
        });
        jPanel1.add(tutorialBotao);
        tutorialBotao.setBounds(49, 402, 840, 70);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selecaoUnidadeBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotaoMouseClicked
        setVisible(false);
        new EscolhaUnidadesTela().setVisible(true);

    }//GEN-LAST:event_selecaoUnidadeBotaoMouseClicked

    private void selecaoUnidadeBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotaoMouseEntered
        selecaoUnidadeBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_selecaoUnidadeBotaoMouseEntered

    private void selecaoUnidadeBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoUnidadeBotaoMouseExited
        selecaoUnidadeBotao.setForeground(Color.white);
    }//GEN-LAST:event_selecaoUnidadeBotaoMouseExited

    private void selecaoJogadorBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoJogadorBotaoMouseClicked
        setVisible(false);
        new EscolhaJogadorTela().setVisible(true);
    }//GEN-LAST:event_selecaoJogadorBotaoMouseClicked

    private void selecaoJogadorBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoJogadorBotaoMouseEntered
        selecaoJogadorBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_selecaoJogadorBotaoMouseEntered

    private void selecaoJogadorBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selecaoJogadorBotaoMouseExited
        selecaoJogadorBotao.setForeground(Color.white);
    }//GEN-LAST:event_selecaoJogadorBotaoMouseExited

    private void documentacaoBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentacaoBotaoMouseEntered
        documentacaoBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_documentacaoBotaoMouseEntered

    private void documentacaoBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_documentacaoBotaoMouseExited
        documentacaoBotao.setForeground(Color.white);
    }//GEN-LAST:event_documentacaoBotaoMouseExited

    private void tutorialBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialBotaoMouseEntered
        tutorialBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_tutorialBotaoMouseEntered

    private void tutorialBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tutorialBotaoMouseExited
        tutorialBotao.setForeground(Color.white);
    }//GEN-LAST:event_tutorialBotaoMouseExited

    private void creditosBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosBotaoMouseClicked
        setVisible(false);
        new CreditosTela().setVisible(true);
    }//GEN-LAST:event_creditosBotaoMouseClicked

    private void creditosBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosBotaoMouseEntered
        creditosBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_creditosBotaoMouseEntered

    private void creditosBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditosBotaoMouseExited
        creditosBotao.setForeground(Color.white);
    }//GEN-LAST:event_creditosBotaoMouseExited

    private void sairBotaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairBotaoMouseClicked

        System.exit(0);
    }//GEN-LAST:event_sairBotaoMouseClicked

    private void sairBotaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairBotaoMouseEntered
        sairBotao.setForeground(new Color(147,87,242));
    }//GEN-LAST:event_sairBotaoMouseEntered

    private void sairBotaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sairBotaoMouseExited
        sairBotao.setForeground(Color.white);
    }//GEN-LAST:event_sairBotaoMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        setVisible(false);
        new PressEnterTela().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel creditosBotao;
    private javax.swing.JLabel documentacaoBotao;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel sairBotao;
    private javax.swing.JLabel selecaoJogadorBotao;
    private javax.swing.JLabel selecaoUnidadeBotao;
    private javax.swing.JLabel tutorialBotao;
    // End of variables declaration//GEN-END:variables
}
